### ISSUE TITLE
after install this module PNPM run dev got error

### ISSUE THREAD

**Issue by azulkipli** [Barbapapazes/nuxt-clarity-analytics#33]
```
Cannot convert undefined or null to object                                                                                       9:55:12 AM

  at Function.assign (<anonymous>)
  at updateRuntimeConfig (node_modules/.pnpm/@nuxt+kit@3.13.1_rollup@4.12.0_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2796:10)
  at setup (node_modules/.pnpm/nuxt-clarity-analytics@0.0.7_rollup@4.12.0_webpack-sources@3.2.3/node_modules/nuxt-clarity-analytics/dist/module.mjs:14:5)
  at normalizedModule (node_modules/.pnpm/@nuxt+kit@3.13.1_rollup@4.12.0_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2136:37)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.10.2_rollup@4.12.0/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.10.2_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_jsukvjbxjfuzu333n4ytpbvp54/node_modules/nuxt/dist/index.mjs:4023:7)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.10.2_@parcel+watcher@2.4.0_@types+node@20.11.19_encoding@0.1.13_eslint@8.57.0_optionat_jsukvjbxjfuzu333n4ytpbvp54/node_modules/nuxt/dist/index.mjs:4121:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.10.3_rollup@4.12.0/node_modules/@nuxt/kit/dist/index.mjs:2570:19)
  at async Object.run (node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/prepare.mjs:53:18)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1777:7) 
```

**Comment by Barbapapazes** [comment]
Thanks for reporting this issue. It was a mistake in the module setup. It's now fixed in`0.0.9`.
